---
title: "upshot-sienna"
author: "Sophia Freuden"
date: "11/19/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(skimr)
library(fs)
library(tidyverse)
```

```{r}
download.file("https://github.com/TheUpshot/2018-live-poll-results/archive/master.zip", destfile = "master.zip")

unzip("master.zip")

x <- read_csv("2018-live-poll-results-master/data/elections-poll-az02-1.csv", col_types = cols(
  .default = col_character(),
  turnout_scale = col_double(),
  turnout_score = col_double(),
  w_LV = col_double(),
  w_RV = col_double(),
  final_weight = col_double(),
  timestamp = col_datetime(format = "")
))
```

```{r}
x

glimpse(x)

# myfiles <- list.files(path="2018-live-poll-results-master/data", pattern="*.csv", full.names=TRUE)
# ^this is one way of doing things, but preceptor doesn't like it :(
```

```{r}
# Make sure you load fs first!

my_list <- dir_ls("2018-live-poll-results-master/data/")

raw <- map_dfr(my_list, .id = "source", ~ read_csv(.x, col_types = cols(
  .default = col_character(),
  turnout_scale = col_double(),
  turnout_score = col_double(),
  w_LV = col_double(),
  w_RV = col_double(),
  final_weight = col_double(),
  timestamp = col_datetime(format = "")
)))

# This will mash all your csv files together in one giant tibble, which isn't very helpful.

# Add .id = "source" into map_dfr to make sure you can see which row came from which csv
```

```{r}
# Create 0/1 for dvote and female

y <- raw %>%
  mutate(female = ifelse(gender == "Female", 1, 0)) %>%
  mutate(dvote = ifelse(response == "Dem", 1, 0)) %>%
  select(female, dvote, response, gender)
```

```{r}
# figure out the relationship between female and dvote

lm(formula = dvote ~ female, data = y)

ggplot(y, aes(x = female, y = dvote)) + geom_jitter() + geom_smooth(method = "lm")
```

